### ISSUE TITLE
建议内置TLS功能

### ISSUE THREAD

**Issue by 1715173329** [lzjluzijie/websocks#1]
建议内置设置TLS证书功能，而并非通过其他软件（例如Caddy/Nginx）转发实现WS over TLS。

**Comment by lzjluzijie** [comment]
嗯，下个版本会加入内置tls，并实现混淆

**Comment by lzjluzijie** [comment]
已经推送到develop分支了，可以试试

**Comment by 1715173329** [comment]
emmmc，有相关说明嘛？看上去貌似是由程序自签一个证书？

**Comment by lzjluzijie** [comment]
对的
go run cmd/websocks-server/main.go --tls
go run cmd/websocks-local/main.go -u wss://localhost:23333/websocks --insecure

**Comment by lzjluzijie** [comment]
如果不明白可以联系我
https://t.me/halulu

**Comment by 1715173329** [comment]
希望能够加入自定义证书的功能
同时也希望能够自定义记录等级

**Comment by lzjluzijie** [comment]
已完成，已经推送到develop分支，明天测试下没问题再release

**Comment by 1715173329** [comment]
吼啊！
