### ISSUE TITLE
很多paas有并发连接限制，最好是能把侦听到的连接合并成一个连接，再在服务器分解开来。

### ISSUE THREAD

**Issue by ghost** [lzjluzijie/websocks#3]
我fork了一份，把不必要的包去掉了，学习websocket的使用。
可以学习一下msocks

**Comment by lzjluzijie** [comment]
好的 不过我也不太懂 可以来TG群讨论

**Comment by lzjluzijie** [comment]
websocket 我准备切换到 github.com/gorilla/websocket
