### ISSUE TITLE
好巧路过

### ISSUE THREAD

**Issue by abersheeran** [lzjluzijie/websocks#4]
刚刚搜 websocks 的时候才发现咱两写了类似的东西，哈哈哈。

这是我的项目 https://github.com/abersheeran/websocks

**Comment by lzjluzijie** [comment]
我这个是半成品自己都不用的，还是用ss好，这个就练练手

**Comment by abersheeran** [comment]
这次国庆让我意识到 SS 已经被精准识别了。平时不封但是会记 IP，时候一到全部玩完。
我有一台阿里的服务器，之前开过一段时间的 SS，后来重装了系统，放了我几个网站在上面。国庆到了，还是被封了。像其他的服务器，国庆的时候全被封了，我一想，再开一个吧。没过几个小时，新开的也没了。

**Comment by lzjluzijie** [comment]
我觉得影响不大。。。主要是ss的生态比较好，再开发新的很难做到实用性，而且我觉得想要识别这种翻墙软件都不是很难。。。

**Comment by abersheeran** [comment]
其实还是有难度的。只不过 SS 树大招风，被人研究了三四年，基本是废了。。
